### ISSUE TITLE
ScreenReader support not working on built version of game

### ISSUE THREAD

**Issue by GrumpyCrouton** [trudeaua21/EasyAccessibilityPackage#24]
The Screen Reader support is working great within the editor, and also works when I Build & Run from Unity, but if I run the game outside of Unity it does not seem to work.

Unity version: 2021.3.16f1
I have followed the instructions found here https://github.com/trudeaua21/EasyAccessibilityPackage/blob/main/Tutorial.md#installation

I have these files: `nvdaControllerClient.dll`, `SAAPI64.dll`, and `Tolk.dll` all in the directory right before my Assets folder.

Currently always using `ScreenReader.StaticReadText` to read text.

Do you have any suggestions, or is there any more information I can provide to try to narrow it down?

**Comment by GrumpyCrouton** [comment]
Nevermind, adding the 3 .dll files to the Build folder (where the .exe is) fixed the issue.

**Comment by trudeaua21** [comment]
Thanks for bringing that to my attention! I updated the tutorial to note that this is needed.
